ship-showdown/models/__init__.py
from .database import db
from .ship import Ship


__all__ = [
    "db",
    "Ship",
]

ship-showdown/models/database.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

__all__ = [
    "db",
]

ship-showdown/models/ship.py
from sqlalchemy import Column, Integer, String, Boolean

from .database import db


class Ship(db.Model):
    __tablename__ = "ships"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    mass = Column(Integer, default=0)
    speed = Column(Integer, default=0)
    jump = Column(Integer, default=0)
    img_id = Column(String, nullable=True)
    deleted = Column(Boolean, nullable=False, default=False, server_default='false')

ship-showdown/__init__.py
__version__ = '0.1.0'

ship-showdown/app.py
from flask import Flask, request, render_template
from flask_migrate import Migrate

import config
from views import product_app
from models import db

app = Flask(__name__)
app.config.update(
    SERVER_NAME="localhost:5000",
    SQLALCHEMY_TRACK_MODIFICATIONS=True,
    SQLALCHEMY_DATABASE_URI=config.SQLALCHEMY_DATABASE_URI,
)
app.register_blueprint(product_app, url_prefix="/ships")

db.init_app(app)
migrate = Migrate(app, db)

@app.route("/", methods=["GET", "POST"])
def index():
    title = "ship showdown"
    name = "Vlad"
    if request.method == "POST":
        name = request.form.get('name', 'Vlad')
    return render_template("index.html", name=name, page_title=title)


@app.route("/hello/")
@app.route("/hello/<string:name>/")
def hello(name=None):
    if name is None:
        name = "World"
    return f"<h1>Hello {name}!</h1>"


@app.route('/post/<int:post_id>/')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post int %d' % post_id

ship-showdown/main.py
from app import app

app.config.update(
    DEBUG=True  # get debug info even on browser page
)

if __name__ == '__main__':
    app.run(
        host="0.0.0.0",
        debug=False
        )

ship-showdown/views/__init__.py
from .product import product_app

ship-showdown/views/product.py
import csv
import pathlib
from flask import Blueprint, render_template, request, jsonify
from werkzeug.exceptions import BadRequest

from models import db, Ship

product_app = Blueprint("product_app", __name__)


@product_app.route("/")
def ship_list():
    ships = Ship.query.filter_by(deleted=False).order_by(Ship.id).all()
    return render_template("ships/index.html", items=ships)


@product_app.route("/add", methods=['POST', 'GET'])
def add_ship():
    msg=''
    # Insert ship into DB
    if request.method == 'POST':
        try: 
            name = request.form.get('name')
            mass = int(request.form.get('mass'))
            speed = int(request.form.get('speed'))
            jump = int(request.form.get('jump'))
            img_id = request.form.get('img_id')
            s = Ship(name=name, mass=mass, speed=speed, jump=jump, img_id=img_id)
            db.session.add(s)
            db.session.commit()
            msg = "Ship successfully inserted"
        except ValueError as ex:
            msg = ex.__str__
    return render_template("ships/add.html", message=msg)


@product_app.route("/<int:identifier>/", methods=['GET', 'DELETE'])
def ship_detail(identifier: int):
    ship = Ship.query.filter_by(id=identifier).one_or_none()
    if ship is None:
        raise BadRequest("No such ship")

    if request.method == 'DELETE':
        ship.deleted = True
        db.session.commit()
        return jsonify(ok=True)

    return render_template(
        "ships/detail.html",
        ship=ship,
    )

ship-showdown/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>
<body>
  <title>
    {% block title %}
    {% endblock %}
  </title>
<div class="container">

<nav class="mb-2 navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('index') }}">Ship Showdown</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('product_app.ship_list') }}">Ships list</a>
      </li>
      <li class="nav-item dropdown">
        <button type="button" class="btn btn-info dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </button>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item disabled" href="#">Personal area</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item disabled" href="#">Contacts</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

  {% block body %}
    Base page
  {% endblock %}
</div>

<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

{% block after_body %}
{% endblock %}
</body>
</html>

ship-showdown/templates/index.html
{% extends 'base.html' %}

{% block title %}
  <h1>Welcome to {{ page_title }}</h1>
{% endblock %}

{% block body %}
  <h1>Greetings, {{ name }}</h1>
{% endblock %}

ship-showdown/templates/ships/add.html
{% extends 'base.html' %}

{% block title -%}
  Add new ship data
{%- endblock %}

{% block body %}
  <h1>Data</h1>
  {% if message %}
    <div class="alert alert-dark" role="alert">
      {{ message }}
    </div>
  {% endif %}
  <form action="" method="POST" class="needs-validation" novalidate>
    <div class="form-row">
      <div class="col-md-6 mb-3">
        <label for="validationCustom01">Ship name</label>
        <input type="text" class="form-control" id="validationCustom01" name="name" value="Sidewinder" required>
        <div class="valid-feedback">
          Correct
        </div>
      </div>
      <div class="col-md-6 mb-3">
        <label for="validationCustom02">Mass</label>
        <input type="text" class="form-control" id="validationCustom02" name="mass" value="1000" required>
        <div class="valid-feedback">
          Correct
        </div>
      </div>
    </div>
    <div class="form-row">
      <div class="col-md-4 mb-3">
        <label for="validationCustom03">Speed</label>
        <input type="text" class="form-control" id="validationCustom03" name="speed" value="300" required>
        <div class="invalid-feedback">
          Valid Integer vaule required
        </div>
        <div class="valid-feedback">
          Correct
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <label for="validationCustom04">Jump range</label>
        <input type="text" class="form-control" id="validationCustom04" name="jump" value="20" required>
        <div class="invalid-feedback">
          Valid Integer vaule required
        </div>
        <div class="valid-feedback">
          Correct
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <label for="validationCustom05">Image Id</label>
        <input type="text" class="form-control" id="validationCustom05" name="img_id" required>
        <div class="invalid-feedback">
          Valid Integer vaule required
        </div>
        <div class="valid-feedback">
          Correct
        </div>
      </div>
    </div>
    <button class="btn btn-primary" type="submit" id="submit-ship">Add ship</button>
  </form>

  <a href="{{ url_for('product_app.ship_list') }}">Back to list ➡ </a>
  <small>&copy; My-Home 2020</small>
{% endblock %}

{% block after_body %}
<script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
{% endblock %}

ship-showdown/templates/ships/detail.html
{% extends 'base.html' %}

{% block title -%}
  Product #{{ product_id }}
{%- endblock %}

{% block body %}
  <h1 class="display-3">{{ ship["name"] }}</h1>
  <hr>
  {% for key in ship %}
    {% if key != "id" %}
    <p class="text-info">{{ key }} is {{ ship[key] }}</p>
    {% endif %}
  {% endfor %}
  <hr>
  <a href="{{ url_for('product_app.ship_list') }}">Back to list ➡ </a>
  <hr>
  <div>
    <button id="delete-product" class="btn btn-danger btn-lg">Delete</button>
  </div>
{% endblock %}

{% block after_body %}
  <script>
  $(function() {
    const name = $('#ship["name"]')
    console.log(name.text())

    $('#delete-product').click(function () {
      $.ajax({
        method: 'DELETE',
        success: function (res) {
          console.log(res)
          console.log(res.data)
        },
        error: function (err) {
          console.error(err)
        },
        complete: function () {
          window.location = '{{ url_for('product_app.ship_list') }}'
        },
      })
    })
  });
  </script>
{% endblock %}

ship-showdown/templates/ships/index.html
{% extends 'base.html' %}

{% block title -%}
  Products
{%- endblock %}

{% block body %}
  <h1>Ships</h1>
  <a href="{{ url_for('product_app.add_ship') }}" class="btn btn-light">Add ship</a>
  <div class="row justify-content-center">
    <div class="card-deck">
      {% for ship in items %}
      <div class="card" style="max-width: 16rem;">
        <img src="{{ url_for('static', filename='img/'+ship.img_id+'.jpg') }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ ship["name"] }}</h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Mass: {{ ship["mass"] }}</li>
            <li class="list-group-item">Sublight speed: {{ ship["speed"] }}</li>
            <li class="list-group-item">Jump range: {{ ship["jump"] }}</li>
          </ul>
          <a href="{{ url_for('product_app.ship_detail', identifier=ship['id']) }}" class="btn btn-primary">Details</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <small>&copy; My-Home 2020</small>
{% endblock %}

{% block after_body %}
  <script>
    $(function () {
      const productItems = $('.product-item')
      console.log(productItems)
    });
  </script>
{% endblock %}